-- CreateTable
CREATE TABLE "Registration" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "firstName" TEXT NOT NULL,
    "fatherName" TEXT NOT NULL,
    "grandfatherName" TEXT NOT NULL,
    "familyName" TEXT NOT NULL,
    "nationalId" TEXT NOT NULL,
    "gender" TEXT NOT NULL,
    "dobISO" TEXT NOT NULL,
    "age" INTEGER,
    "wifeId" TEXT,
    "wifeName" TEXT,
    "wifeDobISO" TEXT,
    "phonePrimary" TEXT NOT NULL,
    "phoneAlternative" TEXT,
    "governorate" TEXT,
    "region" TEXT,
    "neighborhood" TEXT,
    "residenceType" TEXT,
    "dependents_0_2" TEXT,
    "dependents_3_5" TEXT,
    "dependents_6_18" TEXT,
    "dependents_19_59" TEXT,
    "dependents_60_plus" TEXT,
    "males_0_2" TEXT,
    "males_3_5" TEXT,
    "males_6_18" TEXT,
    "males_19_59" TEXT,
    "males_60_plus" TEXT,
    "chronicCount" TEXT,
    "disabilityCount" TEXT,
    "breadwinnerJob" TEXT,
    "housingStatus" TEXT,
    "priorityNeedsJson" TEXT,
    "otherNeeds" TEXT,
    "paymentMethod" TEXT,
    "paymentIdentifier" TEXT
);
